export default {
    mm: {
        language: "mmlanguage",
        english: "mmenglish",
        myanmar: "mm-myanmar",
        profile: "mm-profile",
        logOut: "mm-logout",
        dashboard: "mmDash",
        order: "mmOrder",
        item: "mmItem",
        invoice: "mmInvoice",
        delivery: "mmDelivery",
        warehouse: "mmWarehouse",
        stocks: "mmStocks",
        stockItem: "mmStock Item",
        stockIn: "mmStock In",
        stockOut: "mmStock Out",
        stockReturn: "mmStock Return",
        users: "mmusers",
        customer: "mmCustomer",
        staff: "mmStaff",
        admin: "mmAdmin",
        deliver:"mm-Deliver"
    },
    en: {
        language: "Language",
        english: "English",
        myanmar: "Myanmar",
        profile: "User Profile",
        logOut: "Log out",
        dashboard: "Dashboard",
        order: "Order",
        item: "Item",
        invoice: "Invoice",
        delivery: "Delivery",
        warehouse: "Warehouse",
        stocks: "Stocks",
        stockItem: "Stock Item",
        stockIn: "Stock In",
        stockOut: "Stock Out",
        stockReturn: "Stock Return",
        users: "users",
        customer: "Customer",
        staff: "Staff",
        admin: "Admin",
        deliver:"Deliver",
    },


}